version: 0.0
os: windows
files:
  -  source: \ConsoleProject\ConsoleProject.csproj
     destination: C:\Hello

hooks:
  ApplicationStart:
    - location: \Applicationstart.ps1
      timeout: 300
      runas: Administrator
